apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: e2e-openshift-builds-
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/redhat-openshift-builds/test.git
      - name: revision
        value: avinal/inline-tasks
      - name: pathInRepo
        value: pipelines/konflux-e2e-complete-pipeline.yaml
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
